export enum EnumHelpdeskRole {
  ADMIN = 'ADMIN',
  USER = 'USER',
  DEVELOPER = 'DEVELOPER',
}

export enum EnumMarketplaceRole {
  // Marketplace roles
  ROLE_USER = 'ROLE_USER',
  ROLE_TESTER = 'ROLE_TESTER',
  ROLE_DEVELOPER = 'ROLE_DEVELOPER',
  ROLE_CONSUMER = 'ROLE_CONSUMER',
  ROLE_PROVIDER = 'ROLE_PROVIDER',
  ROLE_PROVIDER_OPEN_DATASET = 'ROLE_PROVIDER_OPEN_DATASET',
  ROLE_HELPDESK = 'ROLE_HELPDESK',
  // Vendor organization roles
  ROLE_VENDOR_USER = 'ROLE_VENDOR_USER',
  ROLE_VENDOR_PROVIDER = 'ROLE_VENDOR_PROVIDER',
  ROLE_VENDOR_CONSUMER = 'ROLE_VENDOR_CONSUMER',
  ROLE_VENDOR_ANALYTICS = 'ROLE_VENDOR_ANALYTICS',
  // External data provider roles
  ROLE_SENTINEL_HUB = 'ROLE_SENTINEL_HUB',
}
